[project]
name = "xmas-lights"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorzero>=2.0",
    "gpiozero>=2.0.1",
    "pydantic>=2.10.4",
    "rpi-gpio>=0.7.1",
]
